services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            PORT: '5005'
        ports:
            - '5005:5005'
